function graphic_setdefault(min_fontsize, varargin)
% here "default" means my own customization 
% graphic_reset % default with min_fontsize = 15
% graphic_reset(min_fontsize) % anything < 0 => default 
% graphic_reset(min_fontsize, [<FIELD>, <VALUE>]) % for additional changes or modification of default  
reset(0); 
if ~exist('min_fontsize', 'var'), min_fontsize = 15; end
if min_fontsize <= 0, min_fontsize = 15; end 

set(0, ...
    'DefaultFigureUnit', 'normalized', ...
    'DefaultFigureColor', 'w', ...
    'DefaultFigureWindowState', 'maximized');

set(0, ...
    'DefaultAxesFontUnits', 'points', ...
    'DefaultAxesFontSize', min_fontsize, ...
    'DefaultAxesLineWidth', 1.5, ...
    'DefaultLineLineWidth', 2, ...
    'DefaultAxesTitleFontWeight', 'normal', ...
    'DefaultAxesTitleFontSize', 1.4, ...
    'DefaultAxesLabelFontSize', 1.25, ...
    'DefaultAxesTickDirMode', 'manual', ...
    'DefaultAxesTickDir', 'out', ...
    'DefaultAxesBoxMode', 'manual', ...
    'DefaultAxesBox', 'off');


set(0, ...
    'DefaultStemlineWidth', 1.5, ...
    'DefaultStemMarker', '.', ...
    'DefaultStemMarkerSize', 10); 

set(0, ...
    'DefaultLegendLocation', 'best', ...
    'DefaultLegendFontSizeMode', 'manual', ...
    'DefaultLegendFontSize', min_fontsize, ...
    'DefaultLegendBox', 'off');

set(0, ...
    'DefaultColorbarFontSizeMode', 'manual', ...
    'DefaultColorbarFontSize', min_fontsize, ...
    'DefaultColorbarBox', 'off', ...
    'DefaultColorbarTickDir', 'out');

set(0, ...
    'DefaultHistogramDisplayStyle', 'stairs');

set(0, ...
    'DefaultImageCdataMapping', 'scaled');

if isunix 
    set(0, 'DefaultAxesFontName', 'FreeSans'); 
    set(0, 'DefaultTextFontName', 'FreeSans'); 
    set(0, 'DefaultUIControlFontName', 'FreeSans'); 
end

set(0,'DefaultFigureCreateFcn',@(fig,~) customized_DefaultFigureCreateFcn(fig));
set(0,'DefaultAxesCreateFcn',@(ax,~) customized_DefaultAxesCreateFcn(ax));

if ~isempty(varargin), set(0, varargin{:}); end

end

function customized_DefaultFigureCreateFcn(fig)
    addToolbarExplorationButtons(fig);
end

function customized_DefaultAxesCreateFcn(ax)
    set(ax.Toolbar,'Visible','off');
end