function create_LFP_band_struct
% References: 
% Levenstein19: Levenstein et al, Nat Com - NREM sleep in the rodent neocortex and hippocampus reflects excitable dynamics 
% Xu19: Xu et al 2019, J Neuro - Sequential Neural Activity in Primary Motor Cortex during Sleep
% Ramanathan15: Ramanathan et al 2015, PLOS Biol - Sleep-Dependent Reactivation of Ensembles in Motor Cortex Promotes Skill Consolidation
% Watson16: Watson et al 2016, Neuron - Network Homeostasis and State Dynamics of Neocortical Sleep

lfp_bands = struct(...
    'slow_wave_Levenstein19', {[0.5, 8]}, ...
    'slow_wave_Ramanathan15', {[0.5, 4]}, ...
    'slow_spindles_Ramanathan15', {[9, 12]}, ...
    'fast_spindles_Ramanathan15', {[13, 16]}, ...
    'slow_wave_Xu19', {[0, 1]}, ...
    'delta_Xu19', {[1, 4]}, ...
    'theta_Xu19', {[4, 7]}, ...
    'alpha_Xu19', {[7, 15]}, ...
    'beta_Xu19', {[15, 31]}, ...
    'gamma_Xu19', {[31, 120]}, ...
    'ratio_theta_delta_Xu19', {{'theta_Xu19', 'delta_Xu19'}}, ...
    'ratio_theta_Watson16', {{[5, 10], [2, 16]}} ...
    ); 

save('lfp_bands.mat', 'lfp_bands'); 
end
    